services:
    shorten-this:
        container_name: shorten-this
        ports:
            - 5000:5000 # <Host Port>:<Container Port (do not change)>
        image: jedrzejme/shorten-this:latest
        restart: unless-stopped