name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get latest Git tag
      id: git_tag
      run: |
        # Fetch tags
        git fetch --tags

        # Get the latest tag
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
        
        # Set as output variable
        echo "::set-output name=LATEST_TAG::$latest_tag"

    - name: Build and push Docker image (multi-platform)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/shorten-this:${{ steps.git_tag.outputs.LATEST_TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/shorten-this:latest
        platforms: linux/amd64,linux/arm64
